- RELEASE.md
- lib/earmark_parser.ex
- lib/earmark_parser/options.ex
- mix.exs
- test/acceptance/regressions/i002-accept-any-struct-as-option_test.exs
Allow client code of Earmark to replace their calls to `Earmark.as_ast` with `EarmarkParser.as_ast` w/o any
changes
> Fixes: #2;

- mix.exs
- Use SPDX license identifier
>  https://hex.pm/docs/publish
>   A list of licenses the project is licensed under. This attribute is required. It is recommended to use SPDX License identifier.
- Fix GitHub URL
> Update hex metadata

- lib/earmark_parser/helpers/pure_link_helpers.ex
- test/acceptance/ast/links_images/pure_links_test.exs
> Retain whitespace when parsing pure links

- lib/earmark_parser/ast/inline.ex
- lib/earmark_parser/helpers/link_parser.ex
- lib/earmark_parser/options.ex
- test/acceptance/ast/links_images/wiki_links_test.exs
- test/support/helpers.ex
(Migrated from https://github.com/pragdave/earmark/pull/377)
This is commonly used in markdown based wikis (for example, Github's wiki).
> Support for "wikilink" style links

- .github/workflows/ci.yml
- lib/earmark_parser/ast/emitter.ex
- lib/earmark_parser/helpers/attr_parser.ex
This change modifies the IAL folding logic from `[c1, c2]` to `"c1 c2"`. 
The current `to_string` behavior of `[String.t]` is concatenation with 
no interleaving spaces, which results in IALs of the form `{:.c1 .c2}` 
being serialized as `<tag class="c1c2">` rather than the intended 
`<tag class="c1 c2">`. After this change, multiple class directives in
an IAL are now serialized correctly in the HTML `class` attribute.
> Join multiple IAL `.class` directives with spaces

- README.md
- lib/earmark_parser.ex
This also threw me off as a non-native speaker, and then I found the following PR https://github.com/pragdave/earmark/pull/218. So this PR replaces the last `iff` with `if and only if`. 😊
> Replace another iff

- lib/earmark_parser/ast/inline.ex
- lib/earmark_parser/options.ex
- test/acceptance/ast/paragraphs_test.exs
We use `EarmarkParser` in [Livebook](https://github.com/livebook-dev/livebook) to parse (Live)Markdown files, but we only need the AST to analyze the block structure (headings, code snippets) and then render most of it back to Markdown. When the inline content is parsed, some information is lost (for example `\` escapes, or emphasis type as in `*a _b_ c*`), which makes it hard to convert the AST back to Markdown.
Since we don't analyze the inline content, ideally we wouldn't even parse it and keep as-is in the AST. This PR enables that by setting using a new `parse_inline: false` option.
This seems to be the minimal change that does the job, but I'm happy to discuss if you have any alternatives in mind!
```elixir
markdown = """
some \\*escaped\\* content
* item _one_
* item _two_
this …
```
> Add an option to disable inline parsing

- README.md
- lib/earmark_parser.ex
- lib/earmark_parser/helpers/footnote_handler.ex
- lib/earmark_parser/helpers/reparse_helpers.ex
- lib/earmark_parser/line.ex
- lib/earmark_parser/line_scanner.ex
- lib/earmark_parser/options.ex
- lib/earmark_parser/parser.ex
- lib/earmark_parser/types.ex
- test/acceptance/ast/comment_test.exs
- test/acceptance/ast/html/block/annotated_block_test.exs
- test/acceptance/ast/list_and_inline_code_test.exs
- test/functional/scanner/line_type_test.exs
Livebook can store outputs in markdown, which can lead
to pretty long code fence tags.
Earmark currently parses all lines, even if they belong to
code fences or html comments. This pull request adds
a small amount of lookahead for those two constructs.
With this, the problematic example report given to us
parses in 10ms, with no timeouts: https://raw.githubusercontent.com/mathiasose/advent-2021/main/aoc.livemd
The lookahead also removes the parallel mapping,
which I have verified to not be efficient in Elixir code
bases, as most lines tend to be short.
I also sneaked in some small optimizations, such as
`length(rest) == 0` which is linear to the size of
`rest` being replaced by `rest == []`.
> Add lookahead for fenced code blocks

- lib/earmark_parser/line_scanner.ex
- test/acceptance/ast/fenced_code_blocks_test.exs
- test/acceptance/ast/html/block/annotated_block_test.exs
This slightly changes the behaviour of invalid Markdown
where a tag is opened and then a fenced code block that
is never closed is within. The previous behaviour already
different from GitHub. We keep the same AST but not we
return warnings.
Closes #77.
> Address regression on closing tags inside fenced blocks

- lib/earmark_parser/helpers/pure_link_helpers.ex
- test/earmark_helpers_tests/pure_link_helper_test.exs
Regex is using character range `+-_` which would match any character between ascii character range of 43 (`+`) to 65 (`_`), which includes invalid characters like `<` and `>`
ref: https://www.rfc-editor.org/rfc/rfc3986#section-2
Fixes #90
> Correct pure link regex to reject invalid characters

- lib/earmark_parser/helpers/pure_link_helpers.ex
- test/acceptance/ast/links_images/pure_links_test.exs
- test/earmark_helpers_tests/pure_link_helper_test.exs
This change is addressing multiple pure-link parsing issue whilst make the implementation closer to GFM [spec](https://github.github.com/gfm/#autolinks-extension-). Please check the new tests for the cases.
The logic of handling braces around pure-link is removed, since it is already handled elsewhere. Moved the associated tests from pure_link_helper_test.exs to acceptance test file.
Note that this is still not handling all the cases from GFM spec such as email links and semicolon at the end
> Fix pure link parsing issues and make it closer to GFM

- lib/earmark_parser/helpers/html_parser.ex
- lib/earmark_parser/parser.ex
- test/acceptance/ast/html/block/annotated_block_test.exs
- test/acceptance/ast/html/block/unannotated_block_test.exs
This slightly changes the HTML representation of the underlying nodes.
Before, this html:
```html
<code>
pre
post
</code>
```
Would come out as:
{:code, [], ["pre", "post"]}
And now it comes out as:
{:code, [], ["pre\npost"]}
While both representations are correct, the second representation where all text nodes are collapsed into one is more common:
```elixir
iex>  Floki.parse_fragment("<code>foo\nbar</code>")
{:ok, [{"code", [], ["foo\nbar"]}]}
```
> Preserve newlines inside HTML code

- lib/earmark_parser/line_scanner.ex
- test/acceptance/ast/html/block/annotated_block_test.exs
The optimisation was introduced in #70 then modified in #79, but with the latter it no longer applies to top-level code blocks (which is primarily what we need), this brings it back.
> Apply fence lookahead optimisation for top-level code blocks

- lib/earmark_parser/line_scanner.ex
- test/acceptance/ast/links_images/wiki_links_test.exs
The line scanner was recognizing the | in a wikilink label as a table column separator. This eventually still got turned into a link, but by then, it was already wrapped in a Para block.
To fix this, eat anything wrapped in double square brackets before looking for the table regex.
@sionide21 here you go, thx again
> Don't wrap labeled wikilinks in p tags

- lib/earmark_parser/line_scanner.ex
- test/acceptance/ast/atx_headers_test.exs
At the moment, parser has hard time parsing notorious `C#` header:
```elixir
iex(1)> EarmarkParser.as_ast("### C#")               
{:ok, [{"h3", [], ["C"], %{}}], []}
iex(2)> EarmarkParser.as_ast("### C# (language)#")
{:ok, [{"h3", [], ["C# (language)#"], %{}}], []}
```
It doesn't look like there is an agreement on how to enable it, but there definitely should be some way to do this! In this PR I altered the regex a bit so that force closing the header would "escape" the content:
```elixir
iex(7)> EarmarkParser.as_ast("### C# #") 
{:ok, [{"h3", [], ["C#"], %{}}], []}
```
> Allow hash sign in header

- lib/earmark_parser/helpers/html_parser.ex
- test/acceptance/ast/html/one_line/attributes_test.exs
I had a real-world Markdown document that looked like this:
```markdown
...
<meta name=”referrer” content=”no-referrer”>
...
```
Note that the `meta` tag's attributes are not using reqular quotes, but left/right double quotes (`&ldquo;` and `&rdquo;` in HTML speak). The attributes are therefore unquoted.
Earmark would raise an error:
```
** (CaseClauseError) no case clause matching: nil
code: assert Training.extract_snippet(input) == expected
stacktrace:
(earmark_parser 1.4.26) lib/earmark_parser/helpers/html_parser.ex:44: EarmarkParser.Helpers.HtmlParser._parse_tag_tail/3
(earmark_parser 1.4.26) lib/earmark_parser/helpers/html_parser.ex:10: EarmarkParser.Helpers.HtmlParser.parse_html/1
(earmark_parser 1.4.26) lib/earmark_parser/ast/renderer/html_renderer.ex:18: …
```
> Support unquoted attrs without space before closing >

- lib/earmark_parser/helpers/string_helpers.ex
There is still a long time for Elixir v1.16
but since I run on the edge, I thought I
would send a PR.
Another solution for the problem is to
use `String.slice(string, ignore..-1//1)`
but that would require Elixir v1.12. The
version in this PR supports earlier
versions too.
> Avoid deprecated negative slice in Elixir v1.16-dev

- README.md
- lib/earmark_parser.ex
- lib/earmark_parser/ast/inline.ex
- lib/earmark_parser/context.ex
- lib/earmark_parser/helpers/ast_helpers.ex
- lib/earmark_parser/options.ex
- test/acceptance/ast/math_test.exs
- test/support/helpers.ex
Adds support for mathematical expressions with `$` and `$$`. This is far from standardised, but GitHub now supports math expressions, so I think having an optional extension is justified.
For more context, now that there are more Nx-based packages it's becoming common to write math expressions docs. Math rendering is left to the user (by extending ExDoc), however there are issues if the math is not understood at parser level. For example `$x *y* x` would be parsed as emphasis, hence destroying the original expression. See https://github.com/elixir-lang/ex_doc/issues/1571.
This implementation should match GitHub for the most part. There are tiny differences, for example:
* GitHub parsing has bugs - in the docs they say `\$` should work within expression, but it actually only `\\$` works
* …
> Add optional support for math syntax

- mix.exs
`dialyxir` is meant to be used with `runtime: false` like shown in their README. Otherwise you get this error:
```elixir
Warning: the `dialyxir` application's start function was called, which likely means you                                                                                                                              
did not add the dependency with the `runtime: false` flag. This is not recommended because                                                                                                                           
it will mean that unnecessary applications are started, and unnecessary applications are most                                                                                                                        
likely being added to your PLT file, …
```
> Add `runtime: false` to `dialyxir` dependency

- test/acceptance/ast/html/permissive_test.exs
- test/acceptance/regressions/i002-accept-any-struct-as-option_test.exs
This resolves the following errors during tests:
warning: single-quoted strings represent charlists. Use ~c"" if you
indeed want a charlist or use "" instead
> Resolve single quote string warnings

- .github/workflows/elixir.yml
This supposes to catch those deprecation warnings in Elixir 1.15,16,17 and Erlang/OTP 25,26,27.
Follow-up discussion in https://github.com/RobertDober/earmark_parser/pull/152#issuecomment-2204012602
> Enable warnings-as-errors in mix test

- lib/earmark_parser/ast/renderer/footnote_renderer.ex
- test/acceptance/ast/footnotes/fn_in_lists_test.exs
- test/acceptance/ast/footnotes/single_footnote_test.exs
- test/support/footnote_helpers.ex
Updated the rendering logic to ensure HTML content is properly rendered instead of being escaped as a string.
Added test cases to verify that %{verbatim: true} is included. 
Fixes https://github.com/elixir-lang/ex_doc/issues/1452
> Footnote rendering escapes HTML bug

- lib/earmark_parser/ast/inline.ex
- test/acceptance/ast/reflink_test.exs
- test/acceptance/bug_test/linked_images_test.exs
Fixes #120 and #149 
There is one test case (`[[]]]text] [reference]\n[reference]: some_url`) that did not have the right expectation. I have changes that test to reflect what Github markdown does but please let me know if this is wrong.
> Fix rendering of multiple images with reflinks
